# Generated by Django 2.1 on 2019-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooyesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='expire_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='total_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
