# Generated by Django 2.1 on 2019-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooyesh', '0002_auto_20190303_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='comment',
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
